### ISSUE TITLE
Inline Javascript will be converted the wrong way

### ISSUE THREAD

**Issue by hirschferkel** [kangax/html-minifier#1061]
`<button id="btn1" class="btn&nbsp;" onclick="myColor('btn1','par1',0,2)">`
and
`<button id="btn1" class="btn " onclick="myColor('btn1','par1',0,2)">`
will be converted to 
`<button class=btn  id=btn1 onclick="myColor(&#34;btn1&#34;,&#34;par1&#34;,0,2)">`
Instead of preserving the space Minifier will add a useless additional space between `class` and `id` which won't work anymore. Is there a fix do preserve the space/&nbsp?

Getting this code from console on minifying:
```
SublimeLinter: ERROR: Unhandled exception:
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/backend.py", line 155, in execute_lint_task
    errors = linter.lint(code, view_has_changed)
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1138, in lint
    return self.filter_errors(self.parse_output(output, virtual_view))
  File "/Users/suer/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1164, in filter_errors
    for error in errors
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1163, in <listcomp>
    error
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1204, in parse_output_via_regex
    for m in self.find_errors(output):
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-contrib-htmlhint.sublime-package/linter.py", line 36, in find_errors
    output_json = sublime.decode_value(output)
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 215, in decode_value
    raise ValueError(err)
ValueError: Error trying to decode value: Expected value in (data):1:64377
```

**Comment by DanielRuf** [comment]
Not reproducable. I would say this is also a bug in Formatter ;-)

![grafik](https://user-images.githubusercontent.com/827205/73667408-82b98a80-46a4-11ea-8639-c925ad638d70.png)

**Comment by DanielRuf** [comment]
As expected:

https://github.com/bitst0rm-pub/Formatter/blob/27dea0804c73b0d2ef43ed6cc25a98ba0399d41e/config/htmlminifierrc.json#L31

`"quoteCharacter": "\"",`

![grafik](https://user-images.githubusercontent.com/827205/73667548-b7c5dd00-46a4-11ea-89ef-7a40fbafb18b.png)

**Comment by hirschferkel** [comment]
You reproduced it. The class is:
`class="btn "` (there is a space in the name of the class)
but after minifying it is 
`class=btn`
> Not reproducable. I would say this is also a bug in Formatter ;-)
> 
> ![grafik](https://user-images.githubusercontent.com/827205/73667408-82b98a80-46a4-11ea-8639-c925ad638d70.png)

**Comment by DanielRuf** [comment]
No, please see the second reply. This is because Formatter has a wrong setting.

**Comment by DanielRuf** [comment]
At least the results looks very off (quoted characters).

> Instead of preserving the space Minifier will add a useless additional space between `class` and `id` which won't work anymore. Is there a fix do preserve the space/&nbsp?

Rechecking that.

**Comment by DanielRuf** [comment]
Probably related to the reordering of the attributes, I would say it's not a big issue for the moment.

**Comment by DanielRuf** [comment]
Well, it is your extra space or `&nbsp;` not a bug to be exact.
You would have to parse it twice.

**Comment by DanielRuf** [comment]
Input (first):

```html
<button id="btn1" class="btn" onclick="myColor('btn1','par1',0,2)">
<button id="btn1" class="btn " onclick="myColor('btn1','par1',0,2)">
```

Output (first):

```html
<button class=btn  id=btn1 onclick='myColor("btn1","par1",0,2)'>and <button class=btn id=btn1 onclick='myColor("btn1","par1",0,2)'>
```

Input (second):

```html
<button class=btn  id=btn1 onclick='myColor("btn1","par1",0,2)'>and <button class=btn id=btn1 onclick='myColor("btn1","par1",0,2)'>
```

Output (second):

```html
<button class=btn id=btn1 onclick='myColor("btn1","par1",0,2)'>and <button class=btn id=btn1 onclick='myColor("btn1","par1",0,2)'>
```

Trailing spaces in attributes are not a good idea in general ;-)
