### ISSUE TITLE
Error in Node from file but ok from module

### ISSUE THREAD

**Issue by toomanylogins** [kangax/html-minifier#1089]
If I run the htmlminifier.js file in dist folder of zip.

```js
var minify = require('./htmlminifier').minify;
var result = minify('<p title="blah" id="moo">foo</p>', {
  removeAttributeQuotes: true
});
result; // '<p title=blah id=moo>foo</p>'
console.log(result);
```

Get error

```
TypeError: minify is not a function
    at Object.<anonymous> (C:\test\Resources\load_minifier.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

If I run as a module

```js
var minify = require('html-minifier').minify;
var result = minify('<p title="blah" id="moo">foo</p>', {
  removeAttributeQuotes: true
});
result; // '<p title=blah id=moo>foo</p>'
console.log(result);
```

Works ok.  Any idea whats going on.
Thanks

**Comment by R4356th** [comment]
The dist folder is for browsers as I understand it. You should use the src directory instead.

**Comment by XhmikosR** [comment]
@R4356th is right.
