### ISSUE TITLE
Error with customAttrCollapse:true and empty custom attributes

### ISSUE THREAD

**Issue by ds82** [kangax/html-minifier#270]
html-minifier fails, if you try to minify that:

```
<div ng-some
   style=""
></div>
```

The line break after the custom attribute is the problem.

Output:

```
TypeError: Cannot call method 'replace' of undefined
    at cleanAttributeValue (/Users/dsaenger/code/firmware/titan-web/titan-gui-web/node_modules/partial2js/node_modules/html-minifier/dist/htmlminifier.js:803:29)
    at normalizeAttribute (/Users/dsaenger/code/firmware/titan-web/titan-gui-web/node_modules/partial2js/node_modules/html-minifier/dist/htmlminifier.js:927:17)
    at Object.HTMLParser.start (/Users/dsaenger/code/firmware/titan-web/titan-gui-web/node_modules/partial2js/node_modules/html-minifier/dist/htmlminifier.js:1135:19)
    at parseStartTag (/Users/dsaenger/code/firmware/titan-web/titan-gui-web/node_modules/partial2js/node_modules/html-minifier/dist/htmlminifier.js:372:17)
    at String.replace (native)
    at new global.HTMLParser (/Users/dsaenger/code/firmware/titan-web/titan-gui-web/node_modules/partial2js/node_modules/html-minifier/dist/htmlminifier.js:236:22)
    at minify (/Users/dsaenger/code/firmware/titan-web/titan-gui-web/node_modules/partial2js/node_modules/html-minifier/dist/htmlminifier.js:1097:5)
```

**Comment by kangax** [comment]
Works for me on http://kangax.github.io/html-minifier/

**Comment by ds82** [comment]
hmm .. strange.
I included a unit test in the PR that fails without my patch ..

**Comment by kangax** [comment]
And you're using the latest version (0.6.8)?

**Comment by ds82** [comment]
Yes. I ran into the issue with the npm version 0.6.8 and reproduced it with hash 3eefb81 of this repo (HEAD before my commit).

**Comment by ds82** [comment]
Ok, I reproduced it with the online demo. The difference it, that I used this option:

```
customAttrCollapse: /.+/
```

.. what I thought would tell html-minifier to collapse all (custom) attributes. With this option, the error occurs. Even in the online demo:

https://cloud.saenger.in/public.php?service=files&t=528d1f987ddb3621beb00833d382ea28&download

**Comment by mgol** [comment]
This has just bitten me hard especially that currently `grunt-angular-templates` swallows the stack trace which makes it hard to pinpoint: https://github.com/ericclemmons/grunt-angular-templates/issues/106

Could you release a new version?

**Comment by kangax** [comment]
Pushed 0.6.9
