### ISSUE TITLE
"ReferenceError: status not defined" crash in node 5.3.0

### ISSUE THREAD

**Issue by prashcr** [kangax/html-minifier#454]
Same build process has worked and still works fine for me in node 5.1.0.  

`html-minifier` version: v1.0.0  
Running on OS X 10.11.2

```
jade -p /Users/prashanthcr/code/surge/hkustakpsi/src/includes < src/contact.jade | \
    html-minifier -o build/contact.html --conservative-collapse --collapse-whitespace --remove-comments
/Users/prashanthcr/.nvm/versions/node/v5.3.0/lib/node_modules/html-minifier/cli.js:346
  cli.exit(status);
           ^

ReferenceError: status is not defined
    at Object.<anonymous> (/Users/prashanthcr/.nvm/versions/node/v5.3.0/lib/node_modules/html-minifier/cli.js:346:12)
    at after (/Users/prashanthcr/.nvm/versions/node/v5.3.0/lib/node_modules/html-minifier/node_modules/cli/cli.js:1057:18)
    at Object.cli.main (/Users/prashanthcr/.nvm/versions/node/v5.3.0/lib/node_modules/html-minifier/node_modules/cli/cli.js:1062:9)
    at Object.<anonymous> (/Users/prashanthcr/.nvm/versions/node/v5.3.0/lib/node_modules/html-minifier/cli.js:106:5)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at Object.exports._errnoException (util.js:855:11)
    at exports._exceptionWithHostPort (util.js:878:20)
    at WriteWrap.afterWrite (net.js:763:14)
make: *** [build/contact.html] Error 1
```

**Comment by bzb-stcnx** [comment]
same error with html-minifier version: v1.0.1 and node 4.2.4
no error with html-minifier version: v1.0.0 (and node 4.2.4)

**Comment by dead-claudia** [comment]
I know exactly what caused it: [this line](https://github.com/kangax/html-minifier/blob/gh-pages/cli.js#L193) was in the [wrong spot](https://github.com/kangax/html-minifier/blob/v1.0.1/cli.js#L346) (i.e. at the bottom of the main script, when it should've been in `runMinify`). It appears fixed now in gh-pages, although @kangax, could you publish a quick patch fix for that?

**Comment by stevenvachon** [comment]
+1

**Comment by kangax** [comment]
Pushed 1.1.0

**Comment by stevenvachon** [comment]
Please publish.

**Comment by kangax** [comment]
I'm investigating minifySVG failure. It doesn't work because svgo API is asynchronous and our parsing can not accomodate that. Tried to work around but not easy. Will have to revert for now coz I don't have much time at the moment.

**Comment by kangax** [comment]
Published 1.1.1

**Comment by stevenvachon** [comment]
Thanks!

**Comment by alexlamsl** [comment]
Fixed by https://github.com/kangax/html-minifier/commit/345e68dea9c634f03a4c1174daf3f0fa2cea331f
