### ISSUE TITLE
why can't I use the tag '<{}>' 

### ISSUE THREAD

**Issue by win7killer** [kangax/html-minifier#711]
when I use the '<{}>' for PHP template(**.html), and I wan't to minify the html, then it has an error that 
`
at new HTMLParser (【mypath】/.2.1.7@html-minifier/src/htmlparser.js:236:13)
    at minify (【mypath】/.2.1.7@html-minifier/src/htmlminifier.js:945:3)
    at Object.exports.minify (【mypath】/.2.1.7@html-minifier/src/htmlminifier.js:1294:10)
    at objectAssign.fileName (【mypath】/.2.0.0@gulp-htmlmin/index.js:22:39)
    at module.exports (【mypath】/.1.0.2@tryit/tryit.js:8:9)
    at minifyHtml (【mypath】/.2.0.0@gulp-htmlmin/index.js:21:9)
    at Transform.htmlminTransform [as _transform] (【mypath】/.2.0.0@gulp-htmlmin/index.js:51:7)
    at Transform._read (【mypath】/.2.1.5@readable-stream/lib/_stream_transform.js:159:10)
    at Transform._write (【mypath】/.2.1.5@readable-stream/lib/_stream_transform.js:147:83)
`

so,  if  the '<{}>' is  special that I can't use it?

**Comment by alexlamsl** [comment]
`<{...}>` is not valid HTML - have you tried specifying `ignoreCustomFragments`?

**Comment by win7killer** [comment]
yes, it works, thx
