### ISSUE TITLE
Cannot parse template angularjs

### ISSUE THREAD

**Issue by vRuslan** [kangax/html-minifier#782]
When Go to minfy the follow HTML  

> 

<input type="text" double-value
       class="form-control widget-textbox {{property.cssClass}}"
       placeholder="{{property.widget.placeholder}}"
       maxlength="{{property.widget.maxLength}}"
       ng-model="widgetValue.value"
       ng-model-onblur ng-change="inputChanged()"
       ng-disabled="!property.writable"
       /> <!--NB type="numbers" doesn't avoid typing of alphabetic chars-  onkeypress="return numbersOnly(this, event, true)" ->

throw following errors: 
Error: Parse Error: <!--NB type="numbers" doesn't avoid typing of alphabetic chars-  onkeypress="return numbersOnly(this, event, true)" ->
    at new HTMLParser (MyPath\html-minifier\src\htmlparser.js:236:13)
    at minify (MyPath\html-minifier\src\htmlminifier.js:952:3)
    at Object.exports.minify (MyPath\html-minifier\src\htmlminifier.js:1305:10)
    at objectAssign.fileName (MyPath\gulp-htmlmin\index.js:22:39)
    at module.exports (MyPath\tryit\tryit.js:8:9)
    at minifyHtml (MyPath\gulp-htmlmin\index.js:21:9)
    at Transform.htmlminTransform [as _transform] (MyPath\gulp-htmlmin\index.js:51:7)
    at Transform._read (MyPath\gulp-htmlmin\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at Transform._write (MyPath\gulp-htmlmin\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (MyPath\gulp-htmlmin\node_modules\readable-stream\lib\_stream_writable.js:347:64)

**Comment by alexlamsl** [comment]
`-->` instead of `->`?
