### ISSUE TITLE
Error: Parse Error

### ISSUE THREAD

**Issue by ghost** [kangax/html-minifier#814]
Having an issue with this html:

```
   <div id="content1">
             <div data-qmod-tool="detailedquotetabchart" data-qmod-params="{&quot;symbol&quot;:&quot;JMDA&quot;,&quot;chfill2&quot;:&quot;21adc3&quot;,&quot;chfill&quot;:&quot;1e99ad&quot;,&quot;svg&quot;:&quot;true&quot;,&quot;chln&quot;:&quot;666666&quot;}" class="qm-wrap qtool"></div>
              </div>
          </div>
          <div id="content2">
              <div data-qmod-tool="fullnews" data-qmod-params="{'symbol':'JMDA','noSrc':'bayaw,ccn'}" class="qm-wrap qtool">
              </div>
          </div>
          <div id="content3">
              <div data-qmod-tool="filings" data-qmod-params="{'symbol':'JMDA'}" class="qm-wrap qtool"></div>
          </div>
```

**Comment by ghost** [comment]
I am using nuxt.js


```
  at new HTMLParser (/Users/jerrickmedia/Documents/jerrick-new/node_modules/html-minifier/src/htmlparser.js:235:13)
    at minify (/Users/jerrickmedia/Documents/jerrick-new/node_modules/html-minifier/src/htmlminifier.js:948:3)
    at exports.minify (/Users/jerrickmedia/Documents/jerrick-new/node_modules/html-minifier/src/htmlminifier.js:1301:10)
    at _callee2$ (/Users/jerrickmedia/Documents/jerrick-new/node_modules/nuxt/dist/nuxt.js:1134:120)
    at tryCatch (/Users/jerrickmedia/Documents/jerrick-new/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/jerrickmedia/Documents/jerrick-new/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/jerrickmedia/Documents/jerrick-new/node_modules/regenerator-runtime/runtime.js:117:21)
    at onFulfilled (/Users/jerrickmedia/Documents/jerrick-new/node_modules/co/index.js:65:19)

```

**Comment by alexlamsl** [comment]
Your example works in http://kangax.github.io/html-minifier/ - which version of `html-minifier` & what options are you using?

**Comment by ghost** [comment]
Looks the issue was fixed in a recent nuxt update. Thanks

**Comment by alexlamsl** [comment]
Good to know :+1:
