### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by extensionsapp** [kangax/html-minifier#858]
Error.

```
7|ramsay.c |     at new HTMLParser (/home/hello.world/node_modules/html-minifier/src/htmlparser.js:235:13)
7|ramsay.c |     at minify (/home/hello.world/node_modules/html-minifier/src/htmlminifier.js:944:3)
7|ramsay.c |     at exports.minify (/home/hello.world/node_modules/html-minifier/src/htmlminifier.js:1297:10)
7|ramsay.c |     at /home/hello.world/routes/website.js:513:32
7|ramsay.c |     at tryHandleCache (/home/hello.world/node_modules/ejs/lib/ejs.js:228:10)
7|ramsay.c |     at View.exports.renderFile [as engine] (/home/hello.world/node_modules/ejs/lib/ejs.js:437:10)
7|ramsay.c |     at View.render (/home/hello.world/node_modules/express/lib/view.js:127:8)
7|ramsay.c |     at tryRender (/home/hello.world/node_modules/express/lib/application.js:640:10)
7|ramsay.c |     at Function.render (/home/hello.world/node_modules/express/lib/application.js:592:3)
7|ramsay.c |     at ServerResponse.render (/home/hello.world/node_modules/express/lib/response.js:971:7)
7|ramsay.c | TypeError: Cannot read property 'replace' of undefined
7|ramsay.c |     at collapseWhitespace (/home/hello.world/node_modules/html-minifier/src/htmlminifier.js:40:15)
7|ramsay.c |     at minify (/home/hello.world/node_modules/html-minifier/src/htmlminifier.js:811:13)
7|ramsay.c |     at exports.minify (/home/hello.world/node_modules/html-minifier/src/htmlminifier.js:1297:10)
7|ramsay.c |     at /home/hello.world/routes/website.js:513:32
7|ramsay.c |     at tryRender (/home/hello.world/node_modules/express/lib/application.js:642:5)
7|ramsay.c |     at Function.render (/home/hello.world/node_modules/express/lib/application.js:592:3)
7|ramsay.c |     at ServerResponse.render (/home/hello.world/node_modules/express/lib/response.js:971:7)
7|ramsay.c |     at renderData (/home/hello.world/routes/website.js:508:21)
7|ramsay.c |     at /home/hello.world/routes/website.js:139:9
7|ramsay.c |     at /home/hello.world/routes/website.js:156:23
```

**Comment by alexlamsl** [comment]
Please provide a reproducible test case.

**Comment by alexlamsl** [comment]
`htmlparser.js:235` refers to the normal Parse Error, so most likely due to invalid input.

**Comment by extensionsapp** [comment]
@alexlamsl Can not you give an empty result instead of an error?

**Comment by extensionsapp** [comment]
In this case, I would like to get the original line `<div> < back </div>` at the output instead of the error.
https://github.com/kangax/html-minifier/issues/712
