### ISSUE TITLE
Error: Parse Error: <>

### ISSUE THREAD

**Issue by dhoko** [kangax/html-minifier#880]
Hi, 

I have a weird issue when I try to minify a template.

```
Module build failed: Error: Parse Error: <>)</p>                                                                           
    at new HTMLParser (/home/dhoko/dev/taf/debug/htmlloader/node_modules/html-minifier/src/htmlparser.js:235:13)           
    at minify (/home/dhoko/dev/taf/debug/htmlloader/node_modules/html-minifier/src/htmlminifier.js:944:3)                  
    at Object.exports.minify (/home/dhoko/dev/taf/debug/htmlloader/node_modules/html-minifier/src/htmlminifier.js:1297:10) 
    at Object.module.exports (/home/dhoko/dev/taf/debug/htmlloader/node_modules/html-loader/index.js:128:26)               
```

### Test string:

1.` <p>Invalid name (Forbidden char. ex: <pre><></pre>)</p>`
2.` <p>Invalid name (Forbidden char. ex: <code><></code>)</p>`
3.` <p>Invalid name (Forbidden char. ex: <>)</p>`
4.` <p>Invalid name (Forbidden char. ex: \<\>)</p>`
5. `<p>Invalid name (Forbidden char. ex: > or <)</p>`
6. `<p>Invalid name (Forbidden char. ex: < or >)</p>`

I tested via gulp, webpack and http://kangax.github.io/html-minifier/

Is there a way to use `<` and `>` inside a string (htmlentities ok)/code/pre ?

Ex:
`<p>Invalid name (Forbidden char. ex:  or <code>></code>)</p>` it works but not `<p>Invalid name (Forbidden char. ex:  or <code><</code>)</p>`

**Comment by alexlamsl** [comment]
Use `&lt;&gt;`.
