### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by meistertoca** [kangax/html-minifier#901]
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: Parse Error: </li>
<li>Airports</li>
<li>Piers Bachelor / Bachelorette Parties</li>
<li>Weddings</li>
<li>Anniversaries</li>
<li>Sweet Sixteen Parties</li>
<li>PromsWine Tours</li>
<li>NYC Sight Seeing</li>
<li>Nights-on the Town</li>
<li>Theaters and Matinees</li>
<li>Casino Tours</li>
<li>And, Every Special Occasion!</li>
</ul>
</div>
<div>
<p>We are proud to be your Excellent Service Travel Partner! To find out more about the services offered by Paradise Limousines, please give us a call. 631.595.1067</p>
</div>
</div>
</section>
    at new HTMLParser (/node_modules/html-minifier/src/htmlparser.js:240:13)
    at minify (/node_modules/html-minifier/src/htmlminifier.js:944:3)
    at Object.exports.minify (/node_modules/html-minifier/src/htmlminifier.js:1304:10)
    at Object.assign.fileName (/node_modules/gulp-htmlmin/index.js:21:39)
    at module.exports (/node_modules/tryit/tryit.js:8:9)
    at minifyHtml (/node_modules/gulp-htmlmin/index.js:20:9)
    at Transform.htmlminTransform [as _transform] (/node_modules/gulp-htmlmin/index.js:50:7)
    at Transform._read (/node_modules/gulp-htmlmin/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/node_modules/gulp-htmlmin/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/node_modules/gulp-htmlmin/node_modules/readable-stream/lib/_stream_writable.js:418:64)

**Comment by meistertoca** [comment]
Never mind. There was an odd character.
