### ISSUE TITLE
`<->` occur error

### ISSUE THREAD

**Issue by deptno** [kangax/html-minifier#946]
I'm using the hexo. Recently updated the package. The following error occurred today

```
    at new HTMLParser (/Users/bglee/workspace/src/github.com/deptno/blog/node_modules/html-minifier/src/htmlparser.js:240:13)
    at minify (/Users/bglee/workspace/src/github.com/deptno/blog/node_modules/html-minifier/src/htmlminifier.js:951:3)
    at exports.minify (/Users/bglee/workspace/src/github.com/deptno/blog/node_modules/html-minifier/src/htmlminifier.js:1306:16)
    at Hexo.OptimizeHTML (/Users/bglee/workspace/src/github.com/deptno/blog/node_modules/hexo-all-minifier/lib/optimizeHTML.js:24:14)
    at Hexo.tryCatcher (/Users/bglee/workspace/src/github.com/deptno/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/bglee/workspace/src/github.com/deptno/blog/node_modules/bluebird/js/release/method.js:15:34)
```

so I am trying to reproduce error, and found.

## reproduce
```
$ git clone https://github.com/kangax/html-minifier.git
$ yarn
$ node ./cli.js s.html
Minification error:
Parse Error: <->
$ cat s.html
<->
```
Is it normal bahavior?

**Comment by alexlamsl** [comment]
> Is it normal bahavior?

Yes, that is invalid HTML - try `&lt:-&gt;`
