### ISSUE TITLE
Error during minify 

### ISSUE THREAD

**Issue by lucaange** [kangax/html-minifier#977]
I am new on gulp 
I have this problems
Someone can help me?
I don't know exactly if this is an issue
`C:\xampp\htdocs\diMassaNew\node_modules\map-stream\index.js:102
        throw err
        ^
Error: Parse Error: <textarea id="roundtrip" cols=32" rows="4" disabled></textarea></th>
<th><iframe id="data" width="80%" height="64"></iframe></th>
</tr>
</tbody></table>

<script src="./base64.js"></script>
<script>
$ = function(id){ return document.getElementById(id) };
function doit(){
    var encoded = Base64[
        'encode' + ($('encodeURI').checked ? 'URI' : '')
     ]($('srctxt').value);
    $('base64').value = encoded;
    if (1 /*@cc_on -1 @*/) {
        $('data').src = 'data:text/plain;base64,'
            + Base64.encode(Base64.decode(encoded));
    }
    $('roundtrip').value = Base64.decode(encoded);
}
</script>
</body>
</html>
    at new HTMLParser (C:\xampp\htdocs\diMassaNew\node_modules\html-minifier\src\htmlparser.js:240:13)
    at minify (C:\xampp\htdocs\diMassaNew\node_modules\html-minifier\src\htmlminifier.js:966:3)
    at Object.exports.minify (C:\xampp\htdocs\diMassaNew\node_modules\html-minifier\src\htmlminifier.js:1326:16)
    at minify (C:\xampp\htdocs\diMassaNew\node_modules\gulp-htmlmin\index.js:16:44)
    at DestroyableTransform._transform (C:\xampp\htdocs\diMassaNew\node_modules\gulp-htmlmin\index.js:38:7)
    at DestroyableTransform.Transform._read (C:\xampp\htdocs\diMassaNew\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\xampp\htdocs\diMassaNew\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\xampp\htdocs\diMassaNew\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\xampp\htdocs\diMassaNew\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (C:\xampp\htdocs\diMassaNew\node_modules\readable-stream\lib\_stream_writable.js:334:11)`

**Comment by mbrandau** [comment]
This is an issue with your HTML code.

    <textarea id="roundtrip" cols=32" rows="4" disabled></textarea>
                                  ^ Missing quotation mark

**Comment by alexlamsl** [comment]
Closing as answered.
