### ISSUE TITLE
Provide a bundled cli.js file for embedding in other projects?

### ISSUE THREAD

**Issue by juj** [kangax/html-minifier#994]
I am looking at incorporating this to Emscripten, in https://github.com/emscripten-core/emscripten/pull/8058

There the size of the minifier at 2.3MB across 212 files was noted to be a concern.

Tried to use rollup to create a minified single file bundle out of html-minifier. Created
`rollup.config.js`:
```
import json from 'rollup-plugin-json';
import babel from 'rollup-plugin-babel';
import resolve from 'rollup-plugin-node-resolve';
import builtins from 'rollup-plugin-node-builtins';
import commonjs from 'rollup-plugin-commonjs';

export default {
  input: 'cli.js',
  output: {
    file: 'html-minifier-bundle.js',
    format: 'cjs'
  },
  plugins: [
    resolve(),
    commonjs(),
    builtins(),
    json(),
    babel({
      exclude: 'node_modules/**'
    })
  ]
};
```
Then run `rollup -c`

That does create a minified 110kB file, but unfortunately running it gives
```
$ node html-minifier-bundle.js html-minifier-bundle.js:4
	throw new Error('Dynamic requires are not currently supported by rollup-plugin-commonjs');
	^

Error: Dynamic requires are not currently supported by rollup-plugin-commonjs
    at commonjsRequire (html-minifier-bundle.js:4:8)
    at Object.<anonymous> (html-minifier-bundle.js:3090:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```
where my capability stopped.

I wonder if it would be possible to provide this kind of bundled file out of html-minifier?

**Comment by alexlamsl** [comment]
See how it is done in https://github.com/kangax/html-minifier/blob/gh-pages/index.html#L324-L325
